name: dsb_trip
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - aioeasywebdav=2.4.0=py37h89c1867_1001
  - aiohttp=3.7.4=py37h27cfd23_1
  - amply=0.1.4=py_0
  - appdirs=1.4.4=py_0
  - async-timeout=3.0.1=py37h06a4308_0
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py37h7b6447c_0
  - biopython=1.78=py37h7b6447c_0
  - blas=1.0=mkl
  - boto3=1.18.16=pyhd3eb1b0_0
  - botocore=1.21.16=pyhd3eb1b0_1
  - bottleneck=1.3.2=py37heb32a55_1
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.14.12=h7636065_2
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - chardet=3.0.4=py37h06a4308_1003
  - coincbc=2.9.8=1
  - configargparse=1.4=pyhd3eb1b0_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - coverage=5.5=py37h27cfd23_2
  - cryptography=3.4.7=py37hd23ed53_0
  - cython=0.29.24=py37h295c915_0
  - datrie=0.8.2=py37h27cfd23_0
  - docutils=0.17.1=py37h06a4308_1
  - dropbox=10.10.0=py37h06a4308_0
  - expat=2.2.10=he6710b0_2
  - fftw=3.3.9=h27cfd23_1
  - filechunkio=1.8=py_2
  - filelock=3.0.12=pyhd3eb1b0_1
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8.1=hfa320df_1
  - ftputil=5.0.1=pyhd8ed1ab_0
  - ghostscript=9.18=1
  - giflib=5.1.4=h14c3975_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.18=pyhd3eb1b0_1
  - glib=2.69.0=h5202010_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-api-python-client=2.15.0=pyhd8ed1ab_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.41.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py37h27cfd23_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py37h06a4308_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.38.0=7
  - grpcio=1.36.1=py37h2157cd5_1
  - harfbuzz=1.7.6=h5f0a787_1
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagemagick=7.0.8_8=pl526h734ff71_1
  - importlib-metadata=3.10.0=py37h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jbig=2.1=hdba287a_0
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jmespath=0.10.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.7.1=py37h06a4308_0
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcrc32c=1.1.1=he6710b0_2
  - libcurl=7.78.0=h0b77cf5_0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20210216=h27cfd23_1
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran=3.0.0=1
  - libgomp=9.3.0=h5101ec6_17
  - libnghttp2=1.41.0=hf8bcb03_2
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.9=he85c1e1_2
  - libtool=2.4.6=h7b6447c_1005
  - libuuid=1.0.3=h1bed415_2
  - libwebp=0.5.2=7
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - logmuse=0.2.6=pyh8c360ce_0
  - markupsafe=2.0.1=py37h27cfd23_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.0.14=py37hd81dba3_0
  - mkl_random=1.0.4=py37hd81dba3_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - multidict=5.1.0=py37h27cfd23_2
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.6.2=pyhd3eb1b0_0
  - numexpr=2.7.3=py37hb2eb853_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauth2client=4.1.3=py_0
  - openblas=0.3.4=ha44fe06_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.1=py37h8c16a72_0
  - pango=1.40.11=h8191d47_0
  - paramiko=2.7.2=py_0
  - pcre=8.45=h295c915_0
  - peppy=0.31.1=pyhd8ed1ab_0
  - perl=5.26.2=h14c3975_0
  - pip=21.2.2=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - pluggy=0.13.1=py37h06a4308_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - protobuf=3.17.2=py37h295c915_0
  - psutil=5.8.0=py37h27cfd23_1
  - pulp=2.5.0=py37h89c1867_0
  - py=1.10.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pygraphviz=1.6=py37h8f50634_0
  - pynacl=1.4.0=py37h7b6447c_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysam=0.16.0.1=py37h45aed0b_3
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37_1
  - pytest=6.2.4=py37h06a4308_2
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h27cfd23_1
  - ratelimiter=1.2.0=py_1002
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - setuptools=52.0.0=py37h06a4308_0
  - simplejson=3.17.3=py37h7f8727e_2
  - six=1.16.0=pyhd3eb1b0_0
  - slacker=0.14.0=py_0
  - smart_open=5.1.0=pyhd3eb1b0_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snakemake=6.7.0=hdfd78af_0
  - snakemake-minimal=6.7.0=pyhdfd78af_0
  - sqlite=3.36.0=hc218d9a_0
  - stopit=1.1.2=py_0
  - tabulate=0.8.9=py37h06a4308_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toposort=1.6=pyhd8ed1ab_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.5.1=py37h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/c.leemans/mydata/miniconda3/envs/dsb_protocol
